### ISSUE TITLE
Fails to deserialize complex JSON object without error

### ISSUE THREAD

**Issue by fwgreen** [IBM-Swift/KituraKit#52]
Assuming that nested JSON objects are not supported (no documentation or tests indicating otherwise), I was expecting some sort of error message.

**Comment by hactar** [comment]
Yes this is less than Ideal - KituraKit should pass the deserialisation error through to us so we can diagnose it properly - at the moment all we get is:

```
604 : A deserialization error occurred. Please ensure that the type of the data being deserialized is correct.
```

Not much help and you have to dig to figure out what was wrong in the data.
