### ISSUE TITLE
Make extensions of public structs public

### ISSUE THREAD

**Issue by krugazor** [IBM-Swift/KituraKit#7]
I wanted to add a header-based authentication, so I just made an extension to the client, adding the headers when needed. But RequestError extensions aren't public, meaning I can't write a func that would use `RequestError(restError: restError)`

Making extensions public for public structs should be the default, being private/protected only when the situation recommends it

**Comment by seabaylea** [comment]
@KyeMaloy97 Can you take a look at this?

**Comment by KyeMaloy97** [comment]
@seabaylea Sure, apologies for the delay but I will take a look at this today.

**Comment by KyeMaloy97** [comment]
@krugazor Do you have a code snippet and the error your receiving so I can recreate your issue and then work on a fix? If you want a more timely conversation and have slack, drop us a message on our Swift Channel [here](http://swift-at-ibm-slack.mybluemix.net/)

**Comment by krugazor** [comment]
Sorry @KyeMaloy97, was super busy at work. Do you still need a sample?

(In a project that uses KituraKit as dependency)
```
extension KituraKit {
   public func get<O: Codable>(_ route: String, additionalHeaders:[String:String], respondWith: @escaping CodableArrayResultClosure<O>) {
        let url = baseURL.appendingPathComponent(route)
        let request = RestRequest(url: url.absoluteString)
        request.headerParameters.merge(additionalHeaders) { (k1, k2) -> String in
            k1
        }
        request.responseData { response in
            switch response.result {
            case .success(let data):
                guard let items: [O] = try? JSONDecoder().decode([O].self, from: data) else {
                    respondWith(nil, RequestError.clientDeserializationError)
                    return
                }
                respondWith(items, nil)
            case .failure(let error):
                Log.error("GET failure: \(error)")
                if let restError = error as? RestError {
                    respondWith(nil, RequestError(restError: restError))
                } else {
                    respondWith(nil, .clientErrorUnknown)
                }
            }
        }
    }
}
```

**Comment by ddunn2** [comment]
@krugazor A [commit](https://github.com/IBM-Swift/KituraKit/commit/335f8aa7a6998c01c1b869882049fc181ea5e348) was pushed a while ago that attempted to resolve this issue. I ran a quick test with the code you provided and it seemed to compile for me. 

I'm just checking in here to see if this issue has been resolved for you as well?

**Comment by ddunn2** [comment]
Closing this issue as it seems it's been resolved!

**Comment by krugazor** [comment]
Sorry mate, this notification was buried under a ton of others, confirming issue solved
